spring.main.web-application-type: none

spring:
  cloud:
    openfeign:
      client:
        config:
          countrylayer:
            url: http://api.countrylayer.com/v2

client:
  url: http://api.countrylayer.com/v2
  key: 9e69860b14f8f46e0c893538968e197c

logging:
  level:
    org:
      springframework:
        web: debug
