spring:
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    ROOT: WARN

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 1
        permittedNumberOfCallsInHalfOpenState: 10
        slowCallDurationThreshold: 4s
        slowCallRateThreshold: 90
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 10
    instances:
      findAllCircuitBreaker:
        baseConfig: default
        waitDurationInOpenState: 20s
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 100ms
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException