spring:
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
  h2:
    console:
      enabled: true
  data:
    rest:
      base-path: /datarest
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  level:
    ROOT: INFO