server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: postgres
    password: postgres
  data:
    mongodb:
      port: 27017
      host: localhost
      database: books
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres
      mode: always
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false

    command:
      version:
        enabled: false
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.psannikov.batch.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
logging:
  level:
    ROOT: WARN