server:
  port: 8089

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/books
    username: postgres
    password: postgres
    initialization-mode: always
  data:
    mongodb:
      port: 27017
      host: localhost
      database: books
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false