spring:
  messages:
    baseName: messages
    encoding: UTF-8
    # Не дает свалиться в системную локаль если не найден файл для переданной в MessageSource
    # Если false то будут браться сообщения из дефолтного файла, если true, то из файла соответствующего системной локали
    fallbackToSystemLocale: false
test:
  rightAnswersCountToPass: 1
  locale: en-us
  fileNameByLocaleTag:
    ru-ru: questions_ru.csv
    en-us: questions.csv