spring:
  messages:
    baseName: "i18n/messages"
    encoding: UTF-8
    # Не дает свалиться в системную локаль если не найден файл для переданной в MessageSource
    # Если false то будут браться сообщения из дефолтного файла, если true, то из файла соответствующего системной локали
    fallbackToSystemLocale: false
test:
  rightAnswersCountToPass: 1
  locale: ru-RU
  fileNameByLocaleTag:
    ru-ru: questions_ru.csv
    en-us: questions.csv