version: '3'
services:
  postgres:
    image: "postgres:16"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=libraryDB

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # Эти свойства перегружают соответствующие в application.yml
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/libraryDB
      - SPRING_DATASOURCE_USERNAME=usr
      - SPRING_DATASOURCE_PASSWORD=pwd
    depends_on:
      - postgres